steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=agoge-website-dev
  - --key=cloudbuild-env
# Insert other build steps here
- name: node
  entrypoint: npm
  args: ['install']
# Deploy
- name: node
  entrypoint: npm
  args: ['run', 'deploy']